supa_url = "https://kqrgsvbchzxdphluxlsm.supabase.co"

supa_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxcmdzdmJjaHp4ZHBobHV4bHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MTYyNzAsImV4cCI6MjA1MTQ5MjI3MH0.jUzOhPbHMHjsCcPGXCGA1qfodhLZ5wVpjfydhxbGOi8"

courier_auth_token = "dk_prod_5QW6D12MD54F8DPJ4E5WC4TF9ZBY"